pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:alpine
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
    volumeMounts:
    - name: cemosa-ca
      mountPath: /usr/local/share/ca-certificates/cemosa
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    volumeMounts:
    - name: cemosa-ca
      mountPath: /usr/local/share/ca-certificates/cemosa
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  volumes:
  - name: cemosa-ca
    configMap:
      name: cemosa-ca-cert
  - name: kaniko-secret
    secret:
      secretName: dockerhub-kaniko2
"""
        }
    }
    stages {
        stage('Build Image') {
            steps {
                container('kaniko') {
                    sh '''
                    /kaniko/executor \
                      --context=dir://$(pwd)/react-spa-aviones \
                      --dockerfile=Dockerfile \
                      --destination=registry.example.com/gabriel/portal-aviones:latest \
                      --verbosity=debug \
                      --skip-tls-verify
                    '''
                }
            }
        }
    }
}
